// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApFydT0Kwm0zbm6hrGoXpMchRGey4jzkY',
    appId: '1:313913777154:web:f01e4f38ef13a4a68b9b1b',
    messagingSenderId: '313913777154',
    projectId: 'nexa-33b28',
    authDomain: 'nexa-33b28.firebaseapp.com',
    storageBucket: 'nexa-33b28.firebasestorage.app',
    measurementId: 'G-TKVNNMF17R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fCOdmagxVs5F12uuzaSPQXMBfmNwoAs',
    appId: '1:313913777154:android:6708c25f4513e3b58b9b1b',
    messagingSenderId: '313913777154',
    projectId: 'nexa-33b28',
    storageBucket: 'nexa-33b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOiNdUMbPtynLBwI8pTlj7v6MVOJXnjo',
    appId: '1:313913777154:ios:59f312a136c17ba88b9b1b',
    messagingSenderId: '313913777154',
    projectId: 'nexa-33b28',
    storageBucket: 'nexa-33b28.firebasestorage.app',
    iosBundleId: 'com.example.nexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzOiNdUMbPtynLBwI8pTlj7v6MVOJXnjo',
    appId: '1:313913777154:ios:59f312a136c17ba88b9b1b',
    messagingSenderId: '313913777154',
    projectId: 'nexa-33b28',
    storageBucket: 'nexa-33b28.firebasestorage.app',
    iosBundleId: 'com.example.nexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApFydT0Kwm0zbm6hrGoXpMchRGey4jzkY',
    appId: '1:313913777154:web:6861e461eb9382978b9b1b',
    messagingSenderId: '313913777154',
    projectId: 'nexa-33b28',
    authDomain: 'nexa-33b28.firebaseapp.com',
    storageBucket: 'nexa-33b28.firebasestorage.app',
    measurementId: 'G-F7JC0GK5PW',
  );
}
